version: '3.0'
services: 
    react-app:
        ports: 
          - '3000:3000'
        build:
          context: .
          dockerfile: Dockerfile.dev
        volumes: 
          - /app/node_modules
#          - .:/app
        stdin_open: true
    react-test:
        build:
          context: .
          dockerfile: Dockerfile.dev
        volumes: 
          - /app/node_modules
#          - .:/app
        command: ["npm","run","test"]

